### ISSUE TITLE
Write a predict.py

### ISSUE THREAD

**Issue by fnunnari** [DFKI-SignLanguage/EASIER-EkmanClassifier#3]
We need a script to just take as input a config/checkpoint (i.e., trained model) and a directory of images.

The output should be a CSV file with a header:

    img_name,cls1, cls2,cls3, ...

and the values of the predictions.

A problem that I foresee, is that the name of the classes are going to be lost when the model is saved.
Maybe, we can add a field into the configuration file (a list of strings) to "remember" the human-readable name of classes that will be used for the CSV output header.

    python predict.py -c <config_file> [-d <device>] --outpredictions <predictions.csv>

**Comment by chiragbhuvaneshwara** [comment]
Implemented predict.py script and integrated it in the main branch in the root dir of the project.
